version: "3"

vars:
  backend_code_dirs: netwarden/ tests/

tasks:
  run:
    cmds:
      - yarn serve --host 0.0.0.0 --port 8000

  install:
    cmds:
      - rm -rf node_modules
      - yarn install
