version: "3"

tasks:
  netbox:
    dir: ~/projects/netwarden-netbox
    cmds:
      - docker-compose up -d

  backend:
    dir: backend
    cmds:
      - poetry run uvicorn netwarden.app:app --host 0.0.0.0 --port 5000

  frontend:
    dir: frontend
    cmds:
      - yarn serve --host 0.0.0.0 --port 8000

  install-backend:
    dir: backend
    cmds:
      - rm -rf .venv
      - poetry install

  install-frontend:
    dir: frontend
    cmds:
      - rm -rf node_modules
      - yarn install

  install:
    cmds:
      - task: install-backend
      - task: install-frontend

  gen-requirements-txt:
    dir: backend
    cmds:
      - poetry export --without-hashes -f requirements.txt > requirements.txt
