version: "3"

vars:
  backend_code_dirs: netwarden/ tests/

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: backend

  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: frontend

tasks:
  netbox:
    dir: ~/projects/netwarden-netbox
    cmds:
      - docker-compose up -d
