name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dmfigol/base-docker-images/python:3.8-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install backend
        run: task install-backend

      - name: Run backend test suite
        run: task backend-test-suite
